### ISSUE TITLE
keep Sketch Cloud reference?

### ISSUE THREAD

**Issue by josefrichter** [bryanberger/abstract-copy-master#1]
Hey, does this approach keep a Sketch Cloud reference for the Master file, please? When I manually export the Master file, I just cannot update the version in Sketch Cloud. Because Abstract basically creates a "new file" after each commit. So the reference to Sketch Cloud is lost and you can only upload it as a completely new file (even if it has the same name).

**Comment by bryanberger** [comment]
This approach copies the sketch file that Abstract generates, so I would assume that reference is no longer there as you describe it.

I personally don't use Sketch Cloud.
